version: '3'
services:
  api-one:
    build:
      context: ./api  # This refers to the current directory, where your Dockerfile is
      dockerfile: Dockerfile
    ports:
      - "8000"
    environment:
      - VERSION=v1

  api-two:
    build:
      context: ./api  # This refers to the current directory, where your Dockerfile is
      dockerfile: Dockerfile
    ports:
      - "8000"
    environment:
      - VERSION=v2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-one
      - api-two
    ports:
      - "8000:80"

